### ISSUE TITLE
export the wav file

### ISSUE THREAD

**Issue by hungvu193** [AxeChen/ChangeVoice#2]
so when i changed the file how can i export it to wav file? Thank you

**Comment by AxeChen** [comment]
谢谢您的支持。 我是为了展示效果才将音频文件放在 res/raw文件夹中，在MainActivity中我将音频文件写入了sdCard。 实际使用中可以直接加载sdCard中的文件。在MainActivity中的startChange方法就是加载sdCard中的文件。

**Comment by hungvu193** [comment]
是的，但我想知道如何导出后，我改变了它的音频文件？ ：D我想分享音频文件

**Comment by AxeChen** [comment]
并没有改变音频文件，只是在播放的时候改变了音频的通道。如果你需要获取到改变通道后保存的音频，这个我也不是很清楚，只能您自己去研究了。谢谢！

**Comment by hungvu193** [comment]
Thanks anyway for your support!
